# Generated by Django 6.0.6 on 2026-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('needs_changes', 'Needs Changes')], default='not_reviewed', max_length=30),
        ),
    ]
