# Generated by Django 6.0.6 on 2026-07-11 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_employment_employee_email_employeeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('MEETING', 'Meeting'), ('HOLIDAY', 'Holiday'), ('TRAINING', 'Training'), ('ANNOUNCEMENT', 'Announcement')], default='ANNOUNCEMENT', max_length=20)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment_company_event',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Optional URL to the related item.', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employment.employment')),
            ],
            options={
                'db_table': 'employment_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
