# Generated by Django 6.0.6 on 2026-07-11 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_companyevent_notification'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='job.job'),
        ),
    ]
