# Generated by Django 6.0.6 on 2026-07-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonIdentityDocument',
        ),
        migrations.DeleteModel(
            name='PersonProfile',
        ),
    ]
