# Generated by Django 6.0.6 on 2026-07-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
