# Generated by Django 6.0.6 on 2026-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='grade',
            field=models.CharField(blank=True, choices=[('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid Level'), ('SENIOR', 'Senior')], max_length=50, null=True),
        ),
    ]
